### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by AlexRMU** [m-bemana/xfields#1]
An error occurs when executing a test command from the documentation:
`!python test.py --dataset dataset\view\island  --type view --dim 5 5  --factor 2 --num_n 4 --nfg 8  --sigma 0.1 --br 1  --scale 90 --fps 90 --savepath results`
```
Traceback (most recent call last):
  File "test.py", line 252, in <module>
    run_test(args)
  File "test.py", line 52, in run_test
    raise NameError('There is no directory:\n %s'%(savedir))
NameError: There is no directory:
 results/datasetviewisland
```
Then I created a directory results/datasetviewisland
```
creating directory results/datasetviewisland/rendered videos
XField type: ['view']
Dimension of input xfield: [5, 5]
output video fps: 90
number of intermediate points for interpolation: 90
Dataset path: datasetviewisland
Traceback (most recent call last):
  File "test.py", line 252, in <module>
    run_test(args)
  File "test.py", line 64, in run_test
    images,coordinates,all_pairs,h_res,w_res = load_imgs(args) 
  File "/content/xfields/load_imgs.py", line 12, in load_imgs
    path_images = os.listdir(args.dataset)
FileNotFoundError: [Errno 2] No such file or directory: 'datasetviewisland'
```

**Comment by m-bemana** [comment]
Were you able to perform training?
` python train.py --dataset dataset\view\island  --type view  --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.1 --br 1 --savepath results `
And did it create the following directories?
`results\island\trained model `
`results\island\saved training`

**Comment by AlexRMU** [comment]
The same thing
`!python train.py --dataset dataset\view\island  --type view  --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.1 --br 1 --savepath results`
```
creating directory results/datasetviewisland/trained model
creating directory results/datasetviewisland/saved training
XField type: ['view']
Dimension of input xfield: [5, 5]
Dataset path: datasetviewisland
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    run_training(args)
  File "train.py", line 69, in run_training
    images,coordinates,all_pairs,h_res,w_res = load_imgs(args) 
  File "/content/xfields/load_imgs.py", line 12, in load_imgs
    path_images = os.listdir(args.dataset)
FileNotFoundError: [Errno 2] No such file or directory: 'datasetviewisland'
```

**Comment by AlexRMU** [comment]
(I run on colab)

**Comment by m-bemana** [comment]
I ran it on colab, and I figured out the problem.
If you change the backslash to the slash in the path, then it should be fine:
`!python train.py --dataset dataset/view/island  --type view  --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.1 --br 1 --savepath results`
Let me know if you still have problems.

**Comment by AlexRMU** [comment]
This problem seems to have disappeared, but a new one has appeared:
```
 ------- Creating the model -------
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    run_training(args)
  File "train.py", line 80, in run_training
    inputs = tf.placeholder(tf.float32,shape=[num_n+1,1,1,len(dims)])    
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```
You need to update tensorflow (https://github.com/theislab/scgen/issues/14)

**Comment by m-bemana** [comment]
We will upgrade the tf version, but for now, please either try to add:

` import tensorflow.compat.v1 as tf`
`tf.disable_v2_behavior()`

or try to install our tested tf version:

`!pip uninstall tensorflow`
`!pip install tensorflow-gpu==1.14.0`

**Comment by AlexRMU** [comment]
`!python test.py --dataset dataset/view/island  --type view --dim 5 5  --factor 2 --num_n 4 --nfg 8  --sigma 0.1 --br 1  --scale 90 --fps 90 --savepath results`

```
---------- Perform Testing ----------
XField type: ['view']
Dimension of input xfield: [5, 5]
output video fps: 90
number of intermediate points for interpolation: 90
Dataset path: dataset/view/island
Downsampling factor: 2
Output resolution: 882 x 882
 Reading image 25 out of 25  Traceback (most recent call last):
  File "test.py", line 252, in <module>
    run_test(args)
  File "test.py", line 116, in run_test
    raise NameError('There is no pretrained model located at dir:\n %s\\trained model\\'%(savedir))
NameError: There is no pretrained model located at dir:
 results/island\trained model\
```

**Comment by m-bemana** [comment]
Hi,
Have you performed the training first for the that scene?
if so, have you checked whether any checkpoints created in the trained model?

**Comment by AlexRMU** [comment]
Hi,
Yes, the training was completed successfully. Yes, the points are created. This is the same error as in training mb.

**Comment by AlexRMU** [comment]
In colab, the training session lasted 6 hours :-/
Can you upload pretrained models to google drive?

**Comment by m-bemana** [comment]
> Hi,
> Yes, the training was completed successfully. Yes, the points are created. This is the same error as in training mb.

Probably it is a path issue, please try to change the `line 111` in the `test.py`
from
    `ckpt=tf.train.get_checkpoint_state("%s\\trained model\\"%(savedir))`
to 
   `ckpt=tf.train.get_checkpoint_state("%s/trained model/"%(savedir))`

let me know whether it could resolve it.

**Comment by AlexRMU** [comment]
```
NameError: There is no pretrained model located at dir:
 results/island\trained model\
```
This folder is empty, although I completed the training. But in the file train.py I replaced 100,000 iterations with 10,000.

**Comment by AlexRMU** [comment]
> In colab, the training session lasted 6 hours :-/
> Can you upload pretrained models to google drive?

?

**Comment by m-bemana** [comment]
> ```
> NameError: There is no pretrained model located at dir:
>  results/island\trained model\
> ```
> 
> This folder is empty, although I completed the training. But in the file train.py I replaced 100,000 iterations with 10,000.

Hi, the problem is the directory path separator which needs to be '/' for unix based machines and I fixed it in the code.

**Comment by m-bemana** [comment]
> > In colab, the training session lasted 6 hours :-/
> > Can you upload pretrained models to google drive?
> 
> ?

Please find below the pretrained model for the Island scene :
https://drive.google.com/drive/folders/1aHWOukagzg_9j-_Ar6kIg0yT7eERu-Lo?usp=sharing

**Comment by AlexRMU** [comment]
Everything works fine. But pretrained shows a bad result and you still need to train
