### ISSUE TITLE
Artifacts while using the model for other datasets

### ISSUE THREAD

**Issue by dhawals1939** [m-bemana/xfields#3]
Hello,
We have been using your repository to train on different scenes. The results are great when we used the data provided by you. 

When we were trying to use the data provided in the link below. The results were not so good. Can we know, is there a limitation in the method? We were looking for the novel view generation aspect of the paper. Any help would be appreciated. 

We tried to keep the change in two consecutive frames to be minimal, using NeRF++ novel views.

[Link to data used](https://iiitaphyd-my.sharepoint.com/:f:/g/personal/dhawal_sirikonda_research_iiit_ac_in/EvKeaprJMblJjkVOmKXHYJwBaViq-MeQPZ70Zg1UhAhT1w?e=s6EuSQ) The data was generated from NeRF++ novel views using the Trucks scene.

**Comment by m-bemana** [comment]
Hello,

The method right now is not designed to work with unstructured captures. But, for what you tried so far, what was the input coordinates to network?

**Comment by dhawals1939** [comment]
```python train.py --dataset our_data_path  --type view  --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.5 --br 1 --savepath results/```

We used the above setting.
We took the 5 frames keeping the y level constant and changing the x slightly. And we have taken 5 different values of y. So totally 5x5 25 frames.

**Comment by m-bemana** [comment]
I started to train it, meanwhile can you share the result you got (flow or reconstruction image or video) maybe I can understand your problem?

**Comment by dhawals1939** [comment]
[Results](https://iiitaphyd-my.sharepoint.com/:f:/g/personal/dhawal_sirikonda_research_iiit_ac_in/Esco7wXYK05Ltyo5RTqrgC4BPqm7RyA7mIA2d6RcoYemhQ?e=aRahri)

**Comment by m-bemana** [comment]
Hello,

I did the training with the command line you sent:
``` python train.py --dataset "dataset/Truck Nerf Gen" --type view --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.5 --br 1 --savepath results/ ```

I did the test with the command line:
``` python test.py --dataset "dataset/Truck Nerf Gen" --type view --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.5 --br 1 --savepath results/ ```

the result look better, here is what I got:

[Truck Nerf Gen.zip](https://github.com/m-bemana/xfields/files/5882494/Truck.Nerf.Gen.zip)

**Comment by dhawals1939** [comment]
Thanks, I will re-train on a different machine, strange that we could not get the same results despite having a similar setup. Your results look consistent.

**Comment by dhawals1939** [comment]
Hi,

We made the following change to the code and the results match with what you have provided us for the "Truck Nerf Gen" data.
The file `load_imgs.py` has `path_images` which were not being sorted in the Linux environment.

I had changed the code in the `load_images.py` file to the following

```
  print("Dataset path: %s"%(args.dataset))
  path_images = os.listdir(args.dataset)
  print('Before sort', path_images)
  path_images.sort()
  print('After sort', path_images)
```
The output of those lines are as follows:
```
Before sort ['000186.png', '000182.png', '000194.png', '000197.png', '000180.png', '000181.png', '000196.png', '000179.png', '000177.png', '000174.png', '000190.png', '000185.png', '000178.png', '000183.png', '000176.png', '000193.png', '000188.png', '000191.png', '000189.png', '000175.png', '000187.png', '000184.png', '000173.png', '000192.png', '000195.png']
After sort ['000173.png', '000174.png', '000175.png', '000176.png', '000177.png', '000178.png', '000179.png', '000180.png', '000181.png', '000182.png', '000183.png', '000184.png', '000185.png', '000186.png', '000187.png', '000188.png', '000189.png', '000190.png', '000191.png', '000192.png', '000193.png', '000194.png', '000195.png', '000196.png', '000197.png']
```
So the sort function seems to fix the issue.

Now the results are matching up with yours (except used fps as 23 while running the test).
[Result](https://user-images.githubusercontent.com/16517445/106615876-e665e480-6592-11eb-8616-363df568d135.mp4)

You can close the thread. Thanks for the help.
