### ISSUE TITLE
Why my training result videos is not good?

### ISSUE THREAD

**Issue by vicdxxx** [m-bemana/xfields#5]
Hi, guys 
    I just run your official code and official dataset, but my result videos is not good except for eiffel
there is an example

![image](https://user-images.githubusercontent.com/14140837/108467402-1b2aa900-72c0-11eb-95c6-411d50a5a408.png)

Could you give some suggestions?

**Comment by JayFoxRox** [comment]
It could be https://github.com/m-bemana/xfields/issues/3#issuecomment-771685493 which hasn't made it into this repository.
