### ISSUE TITLE
Compressed flow representation for view

### ISSUE THREAD

**Issue by zzyunzhi** [m-bemana/xfields#6]
Hi, 
Thanks a lot for the great work! I have one question regarding flow computation. 

In the paper Section 4.2.4 you mentioned that you compute the flow Jacobian for depth field based on closed form reprojection, but basd on the code [here](https://github.com/m-bemana/xfields/blob/6134d4575049fc0fff01c4cf7144473cb94ef7a5/blending.py#L103) it seems that depth field is treated the same way as light and time?

**Comment by m-bemana** [comment]
Hi, 
thank you for your interest in our work.
one channel is enough to represent the depth field, although for sake of  completeness we also consider 2d flow for the depth field. This 2d assumption could also compensate for inaccuracies in regular grid capturing.

**Comment by zzyunzhi** [comment]
Hi, 
So to make it clear, in the implementation you did not use 1d depth field, but used 2d flow for all three types (view, light, time)? 
Apart from this, do you have the intrinsic and extrinsic parameters for images in the dataset?
Thanks.

**Comment by m-bemana** [comment]
Hi, 
yes, we used 2d flow for all three types. 
As we worked with a regular LF grid, we did not estimate the camera parameters, and these parameters are not available.

**Comment by zzyunzhi** [comment]
Thanks for the reply! Closing the issue now.
